apiVersion: apps/v1
kind: Deployment
metadata:
  name: spingbootdemo-deployment
  labels:
    app: spingbootdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spingbootdemo
  template:
    metadata:
      labels:
        app: spingbootdemo
    spec:
      containers:
      - name: spingbootdemo-container
        image: spingbootdemo.azurecr.io/spingbootdemo:latest  # will be replaced by sed in pipeline
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: acr-auth   # Replace with your actual secret name if different
---
apiVersion: v1
kind: Service
metadata:
  name: spingbootdemo-service
spec:
  type: LoadBalancer
  selector:
    app: spingbootdemo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
